### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [kemitchell/spdx-correct.js#1]
Would you please create a LICENSE file, complete with your copyright information and the text of the Apache Software License 2.0?  That makes it a lot easier for people like myself who package up your module for Linux distributions.

**Comment by kemitchell** [comment]
Mind me asking which distro packages individual npm packages?

**Comment by jaredsmith** [comment]
In this case, I'm packaging up spdx-correct for Fedora, RHEL, and CentOS.

**Comment by kemitchell** [comment]
34a629b586803419744409f5414e398bbf5782b1

Landed as v1.0.2.
