### ISSUE TITLE
no support for SPDX expressions

### ISSUE THREAD

**Issue by slang800** [kemitchell/spdx-correct.js#2]
For example, `(ISC OR GPL-3.0)` gets "corrected" to `GPL-3.0`. Maybe this should feature should be a part of a separate package, but it seems related enough to bring up here.

**Comment by kemitchell** [comment]
Thanks for the bug report. `(ISC OR GPL-3.0)` should be recognized as a valid expression and left alone. I'm not sure why it isn't.

spdx-correct was one of my first packages on SPDX, and is probably behind. I will make a note to look into it when I can.

In the meantime, mind me asking what use you've found for SPDX-correct, or how you ran into it?

**Comment by slang800** [comment]
Cool, thanks!

And I found it by searching npm, and am using it in this project: https://github.com/slang800/fixpack for automatically correcting package.json license fields.

**Comment by kemitchell** [comment]
I use fixpack!

Back to you when I can.

**Comment by drewfish** [comment]
I'm running into this too. I'm not the author of any of these packages, just trying to audit their licenses to see if I can use them.

* https://github.com/jrburke/amdefine/blob/e59edc9da24404ec7937098e3992f8fb0e260be7/package.json#L7
* https://github.com/dominictarr/rc/blob/132062de0e61881a025cc4784d9a2798409c2bf1/package.json#L14
* https://github.com/kemitchell/spdx-expression-parse.js/blob/326b222ed9e89e9ef472656e9970649b9ee4e8f3/package.json#L29

**Comment by drewfish** [comment]
Looks like this got published in spdx-correct@2.0.0. Thanks!
