### ISSUE TITLE
It probably shouldn't correct `UNLICENSED` to `Unlicense`.

### ISSUE THREAD

**Issue by geekytime** [kemitchell/spdx-correct.js#3]
npm allows private modules to use `UNLICENSED` to describe code that does not grant any sort of license for use or distribution.

Correcting that to `Unlicense` is kind of the opposite of the intended license expression. 😉

**Comment by kemitchell** [comment]
I maintain [validate-npm-package-license](https://www.npmjs.com/package/validate-npm-package-license), which npm CLI uses to do license metadata validation.

`UNLICENSED` is an npm-specific "magic value", not a valid SPDX license expression. This package is for correcting strings to valid SPDX expressions. If you want to allow `UNLICENSED`, you should check for it before calling `spdx-correct`.
